### ISSUE TITLE
Enable hibernation using power-button does not work

### ISSUE THREAD

**Issue by RussH** [elementary/switchboard-plug-power#101]
I have Hibernation working successfully, I can invoke it using "systemctl hibernate" (you do need a little work to get it operational). However it's not invoked by pressing the power button. Is there some config file to amend someplace?

Note: I use hibernation rather than suspend as the battery is fairly dead and doesn't last a few days with suspend.

**Comment by igalic** [comment]
I would also like to use hibernation rather than suspend because i have my disk encrypted. suspend doesn't protect it from anything.

**Comment by cassidyjames** [comment]
This is either a duplicate of #78, or should be moved to the OS repo since this plug is doing what it's supposed to regarding hibernation, it's just not working in the OS itself.
