### ISSUE TITLE
The free time sleep in the power setting is set to never, but it doesn't work.

### ISSUE THREAD

**Issue by illcat** [elementary/switchboard-plug-power#107]
Computer power lights flickering, mouse can not wake up.
Can only be awakened through the keyboard.

**Comment by peteruithoven** [comment]
Thanks for reporting.
"free time sleep" is not a setting I recognize. Do you mean "Suspend when inactive for" or "Turn off display when inactive for"?

>  Can only be awakened through the keyboard.

This is a separate issue. It's also probably not something we can change from these settings. 

> Computer power lights flickering

This is also a separate issue. It's also probably not something we can change from these settings.
