### ISSUE TITLE
Need Shut Down option when pressing power button

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard-plug-power#108]
On pressing power button, the option to shut down the computer is missing.

![screenshot from 2019-02-27 07 23 45](https://user-images.githubusercontent.com/22585732/53477016-c752a400-3a99-11e9-81cf-9f06028a20f7.png)

**Comment by peteruithoven** [comment]
Looking at the dconf editor that option isn't available:
![screenshot from 2019-02-27 10-54-15](https://user-images.githubusercontent.com/523210/53481710-0d9a0a00-3a7e-11e9-8b0e-6fba23acb616.png)
The trick is that we are merly making options available that a external project gives us, in this case the gnome-settings-daemon:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon
I'd suggest opening an issue there if you want this option.
