### ISSUE TITLE
Brightness controls - missing

### ISSUE THREAD

**Issue by Jopp-gh** [elementary/switchboard-plug-power#110]
I have an issue with **brightness controls**, they are **completely missing**. 
I already posted my issue on **stack-exchange** and got very nice support. But we were not able to solve the issue

https://elementaryos.stackexchange.com/questions/18860/no-brightness-controls-after-fresh-install/18862?noredirect=1#comment21738_18862

_My Computer_: Mac OsX, 
_Elementary_: Juno, i installed the newest updates, 
_Plugins_: purged some plugins on stack-exchange

_Current context_ (With Tweaks installed  ^^ ) 
![Screenshot from 2019-04-30 18-20-46-github](https://user-images.githubusercontent.com/48620536/56982776-58b9c180-6b82-11e9-86e1-6c5a7268b07c.png)

I tried to install 3rd party plugins to add brightness settings by my own. These applications were outdated and did not work anymore. The only application available in the AppCenter does not dim enough, not even on max, and interferes with NightLight. If dimmer is on, NightLight switches off and vice-versa

**Comment by IamLizu** [comment]
I think the correct link to the Stack Exchange post is - https://elementaryos.stackexchange.com/questions/18860/no-brightness-controls-after-fresh-install

**Comment by peteruithoven** [comment]
Not sure why you're showing the Nightlight indicator. That's something else. 
The power indicator menu with brightness control:
![Screenshot from 2019-04-30 20 21 19@2x](https://user-images.githubusercontent.com/523210/56984130-9cfa9100-6b85-11e9-927c-0fa04614d89a.png)

I'm assuming it won't show up for you there seeing it's not visible in the System Settings. 

Mac OsX is a operating system. It tells us 0 about your hardware.

**Comment by johans3** [comment]
The nightlight wingpanel is also a kind of screen luminosity control, so i assumed Brightness controls share the same panel.
I used Juno for 2 days out of the box, but after looking thouroughly for brightness controls which i could not find, i tried to install some 3rd pary app to get some brightness control.
The beauty of Juno is its clean uncluttered interface. There is nothing confusing. 

Secondly i thought…Maybe the battery panel is surpressed because my computer is not a laptop.

![Screenshot from 2019-04-30 18-53-28](https://user-images.githubusercontent.com/48620536/56984816-38d8cc80-6b87-11e9-9708-d6f9b5b7943a.png)

**Comment by peteruithoven** [comment]
A relevant Stack Exchange question: https://elementaryos.stackexchange.com/questions/5465/how-to-reduce-the-brightness-of-a-desktop-pc

Looks like the power settings look for a file in `/sys/class/backlight/`, see: 
https://github.com/elementary/switchboard-plug-power/blob/master/src/MainView.vala#L257-L277
Do you have something in `/sys/class/backlight/`?
It's not dependent, as far as I understand it on whether the computer is a laptop.

**Comment by johans3** [comment]
There is nothing inside  `/sys/class/backlight/`
ok, i will create a the file there, logout and report back

**Comment by peteruithoven** [comment]
That's not how that works. You can't just add a file and have it work. 

Please read for example: https://askubuntu.com/questions/894465/changing-the-screen-brightness-of-the-external-screen

I guess the question would be whether we can integrate Brightness Controller into the power settings, but then I wonder why even Ubuntu didn't do that.

**Comment by johans3** [comment]
indeed it does not work this way. I created the file in Downloads and tried to move it to dest directory. Access denied even with sudo
```
cd Downloads
sudo cp MainView.vala /sys/class/backlight/MainView.vala
```

**Comment by johans3** [comment]
i read somewhere online that Ubuntu derivatives suffer from common problems, like the one controlling brightness  adjustments. My battery preference is surpressed somehow, but this issue were there from day one on. Following the installer process, i noted that Juno had ignored various packages during its first install. 

I configured nothing special in the Juno installer on my USB stick (then installing over my HD partition), except the reformatting of my Fat partition i had created before on my Mac, to a linux partition - ext4 to be exact.

**Comment by johans3** [comment]
should i see something useful in: `systemctl list-units --type service` ?
the only line with error is:
`xpra.service                                          loaded failed failed  Xpra System Server`
could not find anything related by searching for keywords like: battery, brightness or their like :(
