### ISSUE TITLE
Add interactive "Prompt to Shut Down" option for Power Button

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-power#111]
This is the behavior common on desktops where pressing the power button shows a GUI prompt to shut down, exposed as "interactive" in GSD. Could potentially supersede #21.

**Comment by lohxx** [comment]
Can I work on this issue?

**Comment by cassidyjames** [comment]
@lohxx absolutely!

**Comment by lohxx** [comment]
How can i procede with code?

**Comment by cassidyjames** [comment]
@lohxx you can check out the README at https://github.com/elementary/switchboard-plug-power. It does assume you're on elementary OS. You should also follow the directions at "The Basic Setup" section of the developer guide: https://elementary.io/docs/code/getting-started#the-basic-setup

Once you're all set, you can fork this repository, make the change, and then submit a Pull Request!

**Comment by lohxx** [comment]
Oh okay, thank you!
