### ISSUE TITLE
Charger disconnect sound played after waking from suspension

### ISSUE THREAD

**Issue by kylrth** [elementary/switchboard-plug-power#114]
The "charger disconnected" sound plays upon waking from suspension if the computer was plugged in when suspended.

Steps to reproduce:

- Turn audio on
- Plug the laptop charger in while the computer is on
- Suspend the laptop
- Disconnect the charger
- Wake from suspension

Let me know if I need to report this elsewhere.

**Comment by lenemter** [comment]
elementary OS doesn't have the charger disconnect sound anymore.
