### ISSUE TITLE
Battery low indication

### ISSUE THREAD

**Issue by swaroopchirayinkil** [elementary/switchboard-plug-power#142]
**In elementaryOS when the battery get's low I'm not getting any indication regarding the the low battery status.**

**_Some times the laptop just turns off and then only I find out the battery fully drained._**

OS details
------
elementary OS 5.1.3 Hera
Built on Ubuntu 18.04.3 LTS
Linux 4.15.0-91- generic
GTK 3.22.30

Machine details
------------
Dual-core Intel ®Core™i5-7200U CPU @2.50GHz
Intel Corporation HD Graphics 620 (rev 02)
4.0 GB memory

**Comment by danrabbit** [comment]
GNOME Settings Daemon's power plugin is responsible for sending low battery notifications. Closing since this cannot be addressed from System Settings and elementary doesn't maintain this component.

OP, please file an issue with GNOME Settings Daemon on GitLab
