### ISSUE TITLE
Changing "Suspension Options" switches Desktop Theme to "Default" (White Theme)

### ISSUE THREAD

**Issue by lorencinibrdev** [elementary/switchboard-plug-power#165]
**Description of the issue:**
On a fully updated "elementary OS 6.0 Next" system, and with the Dark Theme enabled system-wide, when trying to change the "Suspension Options" for the machine, on the Power Plug, the theme goes back to the Default One as soon as an option is selected on the drop-down.

**Before Change:**
![Screenshot from 2020-10-04 17-59-32](https://user-images.githubusercontent.com/4778177/95027072-29a75980-066c-11eb-8b89-bf14893eb36b.png)

**After Changing:**
![Screenshot from 2020-10-04 17-59-57](https://user-images.githubusercontent.com/4778177/95027054-08df0400-066c-11eb-9181-d32598694d11.png)

**Steps to reproduce the behaviour:**
1. Activate the "Dark Theme" on Desktop Plug.
2. Go to "Power Plug"
3. Change the "Suspend when inactive for..." option to any value.
4. Theme should auto-switch to Default White One.

**Expected behaviour**
System theme should not be auto-changed.

**System Info:**
![Screenshot from 2020-10-04 17-58-27](https://user-images.githubusercontent.com/4778177/95026944-40997c00-066b-11eb-8557-6b47792a84da.png)

![Screenshot from 2020-10-04 17-59-00](https://user-images.githubusercontent.com/4778177/95026952-4c853e00-066b-11eb-8fe4-6fccf0b3a4db.png)

**Comment by lorencinibrdev** [comment]
I've noticed the same behaviour happens on the "Date and Time" plug. Just by entering it, whole system theme goes to White:

![Screenshot from 2020-10-12 05-56-51](https://user-images.githubusercontent.com/4778177/95710264-db87ec80-0c4f-11eb-8a5a-f5674bebc33b.png)

**Comment by cassidyjames** [comment]
@lorencinibrdev I can no longer reproduce either of these on a fully updated elementary OS 6 install. Are they still an issue for you?

**Comment by fabiozaramella** [comment]
I can confirm that it's still happening on an updated Odin daily machine.

![Peek 06-11-2020 10-59](https://user-images.githubusercontent.com/5459945/98358788-2282bb00-201f-11eb-8bd0-9417d6985926.gif)

**Comment by lorencinibrdev** [comment]
> I can confirm that it's still happening on an updated Odin daily machine.
> 
> ![Peek 06-11-2020 10-59](https://user-images.githubusercontent.com/5459945/98358788-2282bb00-201f-11eb-8bd0-9417d6985926.gif)

Same here. Weird thing is that this seems to be happening on different modules. I've seen it happening on Power Plug, as well as in Date and Time plug.

**Comment by hanaral** [comment]
I can't reproduce it at all, but I have my dark style preference to sunset to sunrise. Could you see if you can at all reproduce it with the latest builds of System Settings?

**Comment by im-barney** [comment]
I have the same issue as described above. 
Elementary OS 6 Early Access.

**Comment by tintou** [comment]
I don't have this issue here, I need more logs of what is happening.
Can you open a terminal and run `G_MESSAGES_DEBUG=all io.elementary.switchboard` then reproduce the issue and paste the output?
I'd be also interested by the logs provided by `journalctl -b -r` right after you hit the issue.

**Comment by im-barney** [comment]
I went to get the logs but did an update first. Perhaps I shouldn't have?
Can't reproduce the error any more.

**Comment by lorencinibrdev** [comment]
Hi all.

I'm sorry for the delay. As of the current release, i cannot reproduce the issue anymore. Can i close this?

**Comment by im-barney** [comment]
I haven't experienced this since the public release. Happy to close :)
