### ISSUE TITLE
Add show percent in panel

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-power#167]
## Problem

Choosing to show the battery percentage in the panel isn't something you frequently reference or change, so it probably doesn't need to be in the indicator. But there's currently nowhere else to change this setting

## Proposal

Put the setting here so we can remove it from the indicator

**Comment by cassidyjames** [comment]
I'm unsure if we should remove it from the indicator, but it makes sense to have this here, too, regardless. :+1:

**Comment by cassidyjames** [comment]
@hanaral see: https://github.com/elementary/wingpanel-indicator-power/issues/149

**Comment by andirsun** [comment]
As I implement this PR https://github.com/elementary/wingpanel-indicator-power/pull/194 
then I will migrate switch to power settings

**Comment by andirsun** [comment]
@cassidyjames @danrabbit Done ! 
First merge https://github.com/elementary/switchboard-plug-power/pull/193
Then merge https://github.com/elementary/wingpanel-indicator-power/pull/195
