### ISSUE TITLE
ComboBoxes extend to full width of window

### ISSUE THREAD

**Issue by mcclurgm** [elementary/switchboard-plug-power#178]
## What Happened

The ComboBoxes in the settings pane expand to take up the whole width of the window (minus some padding). This is inconsistent with the other panels that are based on the 2 column design like this, with descriptions in a left column and controls on the right. There, the ComboBoxes just take up the necessary width to display their contents.

## Expected Behavior

The ComboBoxes should be sized to match their contents.

## Screenshots

Here's the Power pane:
![power-combobox](https://user-images.githubusercontent.com/29022469/115764628-07a0ca80-a363-11eb-9ef2-5b5e2360581a.png)
And the Keyboard pane, for comparison:
![combobox-keyboard](https://user-images.githubusercontent.com/29022469/115764890-53ec0a80-a363-11eb-83cd-c7d2248fe1d9.png)

### Logs

n/a

## Platform Information

Odin daily, up to date as of 4/22/21

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/switchboard-plug-power/pull/247
