### ISSUE TITLE
Power settings seem doesn't work correctly

### ISSUE THREAD

**Issue by rzamoramx** [elementary/switchboard-plug-power#232]
### What Happened?

When I tried to change the power management mode (power save, balanced, performance) seem doesn't take the change effectively, to probe what governor are using, I ran the command: 

cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

But the log appears still in powersave mode, this occurs even if I grant root access by clicking the unlock button.

### Steps to Reproduce

1. go to Systems settings
2. click on the power option
3. Change power management mode to any other
4. run the command: cpufreq-info | grep "current policy"
5. check the log

### Expected Behavior

The correct power governor.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Quad-Core 11th Gen Intel® Core(TM) i7-1165G7 @ 2.80GHz.
16 GB memory
1 TB storage (NVMe SSD)

Laptop model: Swift-SF514-55T

**Comment by lenemter** [comment]
elementary OS manages power profiles using [power-profiles-daemon](https://gitlab.freedesktop.org/upower/power-profiles-daemon). Report the issue on their bugtracker please :)
