### ISSUE TITLE
Option to disable "suspend" at all.

### ISSUE THREAD

**Issue by cyberplant** [elementary/switchboard-plug-power#39]
In my case, suspend doesn't work on this desktop computer; when my machine enters in suspend mode, it doesn't stop much of the hardware (disks, all fans, etc remains on) and also it never wakes again.. 

So I want to be able to remove/disable the suspend option from the menu, cause I sometimes I'm hurried and press this button instead of "shut down".

Is it possible to add a global variable on this panel to disable it? What do you think about that?

**Comment by kvdz** [comment]
please not you wrote a bug report for the settings plug power,  not the indicator (top right)
this project is only that part in the  settings -> power.

**Comment by danrabbit** [comment]
Closing as "invalid" as this report seems to be about https://github.com/elementary/wingpanel-indicator-session and not this repo

**Comment by cyberplant** [comment]
I expected to have this setting on the power settings on the "system settings" app..

After we settle on the setting, we can focus on the other part.. or am I missing something?
