### ISSUE TITLE
Setting a sleep value has no effect if the screen is set to never turn off.

### ISSUE THREAD

**Issue by Nine-H** [elementary/switchboard-plug-power#41]
I ran my battery down past 0% twice before I figured out why it wasn't sleeping. Laptop batteries aren't cheap.

If you set the screen to never turn off, but set the computer to sleep after 10 minutes of inactivity, i.e: "sleep after a while but don't interrupt me with a disabled screen beforehand or disable the screen on AC", then the laptop happily runs until the battery is completely flat. I think the correct behavior would be sleeping after 10 minutes.

There should probably be an emergency shutdown too, this site says 20%.

http://www.slate.com/articles/technology/technology/2009/10/how_to_charge_your_laptop.html

but that's a separate issue, that I'll let the developers file that bug and decide what the emergency shutdown thresholds should be.

**Comment by lenemter** [comment]
I cannot reproduce the issue on OS 7.1
