### ISSUE TITLE
Detect hardware, not form factor

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-power#51]
https://github.com/elementary/switchboard-plug-power/blob/cf8fd1ca2c68a0ca6d2fdc966957f3994808250e/src/Plug.vala#L235

Instead of trying to find a laptop here we should be smarter and look for backlight, lid, battery etc separately. This would be more robust and support more form factors

**Comment by augustin-b** [comment]
Do you have any idea how to done it?
Shoud we detect for all these things in one bash script or in separate ones or?

I currently made little backlight check and implemented it same way as laptop_detect currently is.

**Comment by augustin-b** [comment]
Check this please:

[./switchboard-plug-power/src/Plug.vala](https://gist.github.com/augustin-b/f625962c66ba5c122da2e742062a73b5)

Build Test:

[./switchboard-plug-power/build$ sudo make install](https://gist.github.com/augustin-b/eeab3b15f9f675e5df685ccfba406a98)

**Comment by danrabbit** [comment]
Hey @augustin-b thanks for looking into solving this issue! Can you do me a huge favor and create branches with pull requests instead of using a gist? That would really help to see what exactly your changes are

**Comment by augustin-b** [comment]
Np, I'll do it.. but first it still needs some work...
