### ISSUE TITLE
meson regression: dbus service installed to wrong location

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-power#74]
The dbus `.service` file is right now installed to

`/usr/libexec/io.elementary.logind.helper.service`

(which is the wrong location), whereas it was previously installed as

`/usr/share/dbus-1/system-services/io.elementary.logind.helper.service`.

**Comment by decathorpe** [comment]
Additionally, the dbus service `.conf` file is no longer installed to

`/etc/dbus-1/system.d/io.elementary.logind.helper.conf`.

**Comment by decathorpe** [comment]
Can confirm that my issues are fixed. Thanks!

**Comment by tintou** [comment]
@decathorpe Thank you for keeping up to date with the changes :)
