### ISSUE TITLE
turn of display when inactive not working E-Juno

### ISSUE THREAD

**Issue by torikulhabib** [elementary/switchboard-plug-power#81]
turn of display when inactive not working
lock screen not working
elementary juno
![screenshot from 2018-03-25 09-21-43](https://user-images.githubusercontent.com/26135527/37871904-25bb5a9a-3024-11e8-9271-cda79b450555.png)

**Comment by Djaler** [comment]
Why you close this? I can confirm this issue on a fresh installed Juno build

**Comment by torikulhabib** [comment]
i try to install ubuntu 18.04 LTS final and i upgrade to JUNO
problem on light-locker-command -l nothing anymore.
problem was fixed..
