### ISSUE TITLE
there is an issue on laptop screen closing 

### ISSUE THREAD

**Issue by mahmodlte** [elementary/switchboard-plug-power#94]
Dear Elementary Developers Team,

there is an issue on laptop screen closing when i close the screen it is not going to sleep or suspend mode it is still working and some day i put my laptop on the bag and i found that it is still working and becomes very hot i hope to fix soon

Thanks
Mahmood

**Comment by 0xBABA** [comment]
I can confirm this as well.
I have my power settings configured for suspend when closing the lid. it sometimes work, sometimes doesn't mostly when it doesn't it just hangs on the glowing e screen and fans go on and off.

**Comment by dpfaffenbauer** [comment]
Also happens to me on a macbook pro mid-2014. When I close the lid, nothing happens, but pressing the power button will put elementary to sleep.

**Comment by jdmg94** [comment]
Almost a year later on an XPS 13 same issue, it gets stuck on the "e" logo and you have to force restart

**Comment by aexley** [comment]
Can confirm this as well on a Lenovo Legion Y530

**Comment by vaclavhlobil** [comment]
Same here on HP Envy

**Comment by grpanho** [comment]
Same here at a Lenovo S145, at the begging it worked but from nothing it stopped. Now when closing the lid it just keep on.

**Comment by MedLabs** [comment]
same problem here, I guess there are some tricks to fix it on stackoverflow.
but still not fixed in 6.1

**Comment by lenemter** [comment]
This might be the issue with kernel/drivers. Closing as out of scope.
